export enum AppRoute {
	AUTH = 'Auth',
	SIGN_IN = 'Sign In',
	SIGN_UP = 'Sign Up',
	EMAIL_VERIFICATION = 'Email Verification',
	RESET_PASSWORD = 'Reset Passrord',
	HOME = 'Home',
	NEWS = 'News',
	NEWS_DETAIL = 'News Details',
	TODO = 'ToDo',
	TODO_IN_PROGRESS = 'ToDo In Progress',
	TODO_DONE = 'ToDo Done',
	TODO_DETAILS = 'ToDo Details',
	PROFILE = 'Profile',
	ABOUT = 'About',
}
